require:
  - rubocop-haml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  Exclude:
    - 'bin/**/*'
    - db/schema.rb
    - 'vendor/**/*'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'
